### ISSUE TITLE
Category Nesting 

### ISSUE THREAD

**Issue by ckyuri** [Sonic-Hedgehog/Voslin-Theme#1]
Minecraft Hosting is a parent of the 2 categories 'Budget Minecraft Hosting' & 'Premium Minecraft Hosting'. 

Default behaviour = hiding 'Budget Minecraft Hosting' & 'Premium Minecraft Hosting' under Minecraft Hosting.

There should be an option to toggle for it to act as default behavior show all.

![firefox_MxRRxrQm1D](https://github.com/user-attachments/assets/e856f5ec-3f9f-4d53-8e21-4bf5d39afb8a)

**Comment by Sonic-Hedgehog** [comment]
@ckyuri Thanks for contacting me, I will check this out.

**Comment by ckyuri** [comment]
Related Issue: 
In screenshot 1, which is the voslin theme applied it only shows the plan underneath the category. 
In screenshot 2, default theme, it shows the the plans and the nested categories. 
*screenshot 2 I accidently cut out the custom plan
![L0XnL2poMT](https://github.com/user-attachments/assets/c9210717-7a59-43eb-9616-275f0344d60e)
![firefox_95om39KcaT](https://github.com/user-attachments/assets/00117f4d-85ee-4fe2-9a52-9ce3fd61ba9e)

**Comment by Sonic-Hedgehog** [comment]
I see the issue. I will fix it as soon as possible. Thank you for reporting.

**Comment by Sonic-Hedgehog** [comment]
@ckyuri [v1.6.1-dev](https://github.com/Sonic-Hedgehog/Voslin-Theme/tree/v1.6.1-dev) please check it out and comment.
