### ISSUE TITLE
Image Displays on categories 

### ISSUE THREAD

**Issue by ckyuri** [Sonic-Hedgehog/Voslin-Theme#2]
Note: The developer build does work on my end for the previous nesting issue so gj on the fix!

The new issue is that the default theme shows images for the categories on the main page but voslin theme hides them until you click on the category. 

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/d1689319-d8e0-46fe-a067-688ad1101466">

As seen above using voslin theme the images are not displayed.

**Comment by Sonic-Hedgehog** [comment]
@ckyuri thanks for reporting. I have found the issue. I will fix it soon and let you know.

**Comment by Sonic-Hedgehog** [comment]
@ckyuri checkout the new commit and let me know if it works as expected: [eb80dbd](https://github.com/Sonic-Hedgehog/Voslin-Theme/archive/eb80dbd.zip)
